name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Ejecuta diariamente
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake Game from Contributions
        uses: Platane/snk@v2
        with:
          github_user_name: marh08192003

      - name: Move Generated Snake to Dist Folder
        run: |
          mkdir -p dist
          mv github-contribution-grid-snake.svg dist/

      - name: Commit and Push the Snake SVG to Output Branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true
